package com.lyl.calendar;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "OVER_TIME".
 */
public class OverTime {

    private Long id;
    private int count;
    /**
     * Not-null value.
     */
    private String cur_month;
    private java.util.Date startTime;
    private java.util.Date endTime;
    /**
     * Not-null value.
     */
    private java.util.Date date;

    public OverTime() {
    }

    public OverTime(Long id) {
        this.id = id;
    }

    public OverTime(Long id, int count, String cur_month, java.util.Date startTime, java.util.Date endTime, java.util.Date date) {
        this.id = id;
        this.count = count;
        this.cur_month = cur_month;
        this.startTime = startTime;
        this.endTime = endTime;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    /**
     * Not-null value.
     */
    public String getCur_month() {
        return cur_month;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setCur_month(String cur_month) {
        this.cur_month = cur_month;
    }

    public java.util.Date getStartTime() {
        return startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getEndTime() {
        return endTime;
    }

    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
    }

    /**
     * Not-null value.
     */
    public java.util.Date getDate() {
        return date;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    @Override
    public String toString() {
        return "OverTime{" +
                "id=" + id +
                ", count=" + count +
                ", cur_month='" + cur_month + '\'' +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                ", date=" + date +
                '}';
    }
}
