package com.lyl.calendar.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.databinding.BaseObservable;
import android.databinding.Bindable;

import com.lyl.calendar.BR;

/**
 * Entity mapped to table "OVER_TIME".
 */
public class OverTime extends BaseObservable {

    private Long id;
    private int count;
    private int job;
    /**
     * Not-null value.
     */
    private String curMonth;
    private java.util.Date startTime;
    private java.util.Date endTime;
    /**
     * Not-null value.
     */
    private java.util.Date date;

    public OverTime() {
    }

    public OverTime(Long id) {
        this.id = id;
    }

    public OverTime(Long id, int count, int job, String curMonth, java.util.Date startTime, java.util.Date endTime, java.util.Date date) {
        this.id = id;
        this.count = count;
        this.job = job;
        this.curMonth = curMonth;
        this.startTime = startTime;
        this.endTime = endTime;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Bindable
    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
        notifyPropertyChanged(BR.count);
    }

    @Bindable
    public int getJob() {
        return job;
    }

    public void setJob(int job) {
        this.job = job;
        notifyPropertyChanged(BR.jobPerformance);
    }

    /**
     * Not-null value.
     */
    @Bindable
    public String getCurMonth() {
        return curMonth;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setCurMonth(String curMonth) {
        this.curMonth = curMonth;
        notifyPropertyChanged(BR.curMonth);
    }

    @Bindable
    public java.util.Date getStartTime() {
        return startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
        notifyPropertyChanged(BR.startTime);
    }

    @Bindable
    public java.util.Date getEndTime() {
        return endTime;
    }

    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
        notifyPropertyChanged(BR.endTime);
    }

    /**
     * Not-null value.
     */
    @Bindable
    public java.util.Date getDate() {
        return date;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDate(java.util.Date date) {
        this.date = date;
        notifyPropertyChanged(BR.date);
    }

}
